[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = { version = "0.6", default-features = false }
nom = "7.1.3"

# https://github.com/eyre-rs/eyre/tree/master/color-eyre#improving-perf-on-debug-builds
[profile.dev.package.backtrace]
opt-level = 3
